// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountRegisterReq {
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
}
